In [6]:
import pandas as pd
# Tells Python to load the Pandas library into its memory.
# It allows you to work with data in rows and columns (called DataFrames).

In [7]:
dataset = pd.read_csv('Salary_Data.csv')
# You are taking a static file on your hard drive (Salary_Data.csv) 
# and bringing it into Python’s active memory as an Dataframe object "dataset"

In [8]:
independent=dataset[["YearsExperience"]]
independent.head()
# In this line we are isolating the specific column 
# which will serve as the "input" for the model.[[...]]: * This is a crucial detail in Pandas. By using double brackets, you are telling Python to keep the output as a DataFrame (a 2D table structure) rather than converting it into a Series
#
# [[...]]: 
# By using double brackets, we are informing python to keep the output as a DataFrame ( table structure) 
# rather than converting it into a Series (list)

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [9]:
dependent=dataset[["Salary"]]
dependent.head()
# In this step, we are defining our Target Variable (the output).
# just like how we did for independent variable, we are going to isolate a specific piece of the data 
# which we will need to be "predicted"

    Salary
0  39343.0
1  46205.0
2  37731.0
3  43525.0
4  39891.0

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(independent, dependent, test_size=0.3, random_state=0)

#one of the critical step in Machine Learning project. 
# we are taking our "Inputs" and "Answers" and shuffling them into different piles 
# to ensure the  model is actually learning and not just registering information.

#The train_test_split function :
# performs a "random slice" of your data. 
# here its like taking 30 rows of data, and allocating into two unequal sets of data.


# function returns four separate variables:
##
# X_train: The 70% of "YearsExperience" for training the model
# X_test: The 30% of "YearsExperience" for testing the model later
# y_train: The 70% of "Salaries"  act as the output or solution key for the training set.
# y_test: The 30% of "Salaries"  check to see if in deed the model's predictions are correct/closer to expected result.

#------------------
# Arguments:
# #------------------
# test_size=0.3: 
# #------------------
# telling machine learning to keep 30% of the data into the "Test" pile 
# And 70% into the "Train" pile. 
# for 30-row datase this translates to 21 rows for training and 9 rows for testing.

#------------------
# Arguments:
# #------------------
# random_state=0:
# #------------------
#This is like a "seed" for splitting the training and testing set.
#
# If 0 is  set (or any fixed number), we will get the exact same split every time you run the code.
# helps in debugging as it ensures results are consistent 
# while we are still writing and checking the script.

In [11]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, y_train)
#--------
#line:1
#--------
#The ImportPythonfrom sklearn.linear_model import LinearRegression
# Here we are using the Linear Regression class/procedure of the sklearn library. 
# This particular routine/template is designed to deduce a straight-line relationship 
# between a cause/input (years of Experience/independent) and an effect/output (corresponding Salary/dependent).

#--------
#line:2
#--------
# Initialization
# regressor = LinearRegression()
# (Building the Brain/computing model for the scenario)
#
# we are creating an "instance" of the model. 
# we have instantiated a model regressor,
# This is a plain slate, it has done no learning yet 
# it is just aware or informed that straight line formula is << y=mx + c >> 
# it is yet to discover what "m" is ==> which is the salary increase per year
  # Also  yet to discover what "c" is ==>  which is the starting salary.

#--------
#line:3
#--------
#regressor.fit(X_train, y_train)
# Training the regressor(fit) regressor.fit(X_train, y_train)
# here machine/model takes 21 rows of training data (X_train and y_train)
# and performs a mathematical calculation called Ordinary Least Squares.
#
#----------------------------------------------------------------
#Refernece : https://en.wikipedia.org/wiki/Ordinary_least_squares
#----------------------------------------------------------------
# Ordinary Least Squares (OLS) is a fundamental, unbiased, linear regression technique 
# that estimates coefficients by minimizing the sum of the squared differences (residuals) 
# between observed and predicted dependent variable values. It fits a straight line (Y=mX +c) 
# that best represents data trends, making it ideal for predictive modeling and interpreting relationships 
# in economics and science
# It finds the "best-fit" line or hyperplane that reduces prediction errors, 
# commonly used to analyze relationships between independent and dependent variables
#----------------------------------------------------------------    
# So the end result:
#-----------------------
#It draws a line through your data points and keeps adjusting it 
# until the distance between the line and the actual data points is as small as possible.
#-----------------------
# once << regressor.fit() >> finishes running, our model is ready: now the following are calculated
# Coefficient (Slope): "m" which is how much the salary increases for every 1 year of experience.
# Intercept(bias): the starting salary is for someone has 0 years of experience.

LinearRegression()

In [12]:
weight=regressor.coef_
#print(regressor.coef_)
weight

# In this step, we are looking inside the trained model
# to check what it has learned from our data.
# regressor.coef_:: 
#     coef_ stands for Coefficient. 
#     In mathematics (and specifically in the equation of a line << y = mx + c  >>, 
#     this is the << m  >> or the Slope. 
# #---------------------------------------------------------------- 
# In Scikit-learn, attributes that end with an underscore 
#     (like coef_ or intercept_) ususally refers to Estimated Attributes.
# #---------------------------------------------------------------- 
#     This means they didn't exist when we first instantiated the model; 
#     they were  << computed >> after we ran the .fit() method/procedure.

array([[9360.26128619]])

In [13]:
bias= regressor.intercept_
bias
#-------------------
# regressor.intercept_:
#-------------------
# In the equation of a line << y = mx + c  >>,  this is the << C >> or the intercept. 
# In statistics, it is called the << Intercept >>; in Machine Learning, we call it the << Bias >>.
# This the predicted Salary when Years of Experience is 0.

array([26777.3913412])

In [15]:
y_pred=regressor.predict(X_test)

# Here we are handing the model the X_test set of data 
# (the years of experience for the 30% of people which was set aside earlier).
#-------------------
#The model takes its internal formula 
# "Salary = Weight times(*) Experience + Bias >> 
# and applies it to every row in X_test.
#-------------------
#The model does not see the actual salaries (y_test) during this step. 
# It is making prediction based strictly on the pattern it learned during training.
#-------------------

In [17]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

# this is the << moment of truth >>
#-------------------
# from sklearn.metrics import r2_score:
#-------------------
# we are using the R-Squared tool from the sklearn.metrics library. 
# which is a standard "KPI" (Key Performance Indicator) for regression models.
#-------------------
#-------------------
#r2_score(y_test, y_pred):
#-------------------
#-------------------
# we are giving the function two lists: 
# the Actual Salaries (y_test) and 
# the Model's prediction  (y_pred).

# The function compares how close the predictions are to the actual value. 
# It measures how much of salaries varies 
# happens based on the number of years of experience.

In [66]:
r_score

0.9740993407213511

In [18]:
filename="finalized_model_linear.sav"

In [22]:
import pickle
pickle.dump(regressor, open(filename,"wb"))

# Model Persistence:
# import pickle loads a built-in Python library used for "serializing" and "deserializing" Python objects.

# Serializing (Pickling): Converting our trained regressor in memory 
# into a stream of bytes that can be saved as a file on our disk and re-use it.

# Deserializing (Unpickling): Loading that file back into a Python script
# later so you can use the model instantly without having to re-run the fit() command.

# "wb" ==> Write Binary.

In [76]:
result

array([[148460.78806172]])

In [37]:
user_input1=int(13)
input=13
result=loaded_model.predict([[user_input1]])

C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [36]:
# Each inner list represents a new "row" (a new person)
multiple_inputs = [[5], [10], [13], [15], [20]]

results = loaded_model.predict(multiple_inputs)

# This will print an array of 5 predicted salaries
print(results)

[[ 73578.69777217]
 [120380.00420313]
 [148460.78806172]
 [167181.3106341 ]
 [213982.61706507]]

C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(